surface.CreateFont("Eblanograd_Big", {
    font = "Eblanograd_Big", 
    size = 200, 
    weight = 1500, 
    antialias = true, 
    additive = true, 
    outline = false, 
    blursize = 0, 
    scanlines = 0, 
    italic = false, 
    underline = false,
    strikeout = false,
    rotary = false, 
    shadow = true, 
    additive = false, 
    outline = false, 
})

surface.CreateFont("Eblanograd_Small", {
    font = "Eblanograd_Small", 
    size = 35, 
    weight = 5020, 
    antialias = true, 
    additive = true, 
    outline = false, 
    blursize = 0, 
    scanlines = 0, 
    italic = false, 
    underline = false,
    strikeout = false,
    rotary = false, 
    shadow = true, 
    additive = false, 
    outline = false, 
})

surface.CreateFont("Eblanograd_Painhud", {
    font = "Roboto-BlackItalic", 
    size = 20, 
    weight = 42130, 
    antialias = true, 
    additive = false, 
    outline = false, 
    blursize = 0, 
    scanlines = 0, 
    italic = false, 
    underline = false,
    strikeout = false,
    rotary = false, 
    shadow = false, 
    additive = false, 
    outline = false, 
})

surface.CreateFont("Eblanograd_Lite", {
    font = "Eblanograd_Lite", 
    size = 35, 
    weight = 5020, 
    antialias = true, 
    additive = true, 
    outline = false, 
    blursize = 0, 
    scanlines = 0, 
    italic = false, 
    underline = false,
    strikeout = false,
    rotary = false, 
    shadow = true, 
    additive = false, 
    outline = false, 
})